"use client"
import { AlertTriangle, BrainCircuit, Check, CircleDot, EyeOff, Gauge, ShieldCheck } from "lucide-react"
import { useLang } from "@/lib/language-provider"
import { localized } from "@/lib/localized"

const context = [
  { group: "FOUNDER RULES", icon: ShieldCheck, items: [["Trust > Animation", "rule.financial.trust-first", "1.00"], ["Information before decoration", "rule.design.information-first", "1.00"]] },
  { group: "RELEVANT DECISIONS", icon: Check, items: [["HTX-inspired institutional fintech", "decision.tradespan.visual-language", ".96"], ["Deep blue runtime surface", "decision.sera.console-dark", ".92"]] },
  { group: "PREVIOUS EXPERIENCE", icon: AlertTriangle, items: [["React stage effect failed", "experience.ui.stage-effect", ".88"], ["Generic SaaS cards weakened hierarchy", "experience.dashboard.generic", ".84"]] },
]
export default function ContextPage(){
  const { lang } = useLang(); const c = (zh:string,en:string) => localized(lang,zh,en)
  const groupLabel: Record<string,[string,string]> = {"FOUNDER RULES":["创始人规则","FOUNDER RULES"],"RELEVANT DECISIONS":["相关决策","RELEVANT DECISIONS"],"PREVIOUS EXPERIENCE":["历史经验","PREVIOUS EXPERIENCE"]}
  return <div className="command-page"><header className="page-head"><div><span>CONTEXT OS / LIVE RUNTIME</span><h1>{c("进入智能体的思维", "Inside the agent's mind")}</h1><p>{c("查看上下文治理器在执行前注入、排序和排除的全部信息。", "See exactly what the Context Governor injected, ranked and excluded before execution.")}</p></div><div className="runtime-pill"><i/> LIVE · FRONTEND AGENT</div></header><div className="context-layout"><section className="terminal-panel context-main"><div className="mission-brief"><span>{c("当前任务", "CURRENT MISSION")}</span><h2>Build the TradeSpan landing page</h2><p>{c("交付一个可信的机构级界面，把架构转化为清晰可理解的产品故事。", "Deliver a trusted institutional interface that turns architecture into an intelligible product story.")}</p><div><b>{c("结果","Outcome")}</b><span>Production-ready frontend</span><b>{c("权威","Authority")}</b><span>Founder</span><b>{c("运行时","Runtime")}</b><span>Codex / Mac</span></div></div>{context.map(({group,icon:Icon,items})=><div className="context-group" key={group}><h3><Icon />{c(groupLabel[group][0],groupLabel[group][1])}<span>{items.length} {c("已注入","INJECTED")}</span></h3>{items.map(([title,id,score])=><div className="context-item" key={id}><CircleDot/><div><strong>{c({"Trust > Animation":"信任优先于动效","Information before decoration":"信息优先于装饰","HTX-inspired institutional fintech":"HTX 启发的机构级金融科技","Deep blue runtime surface":"深蓝运行时界面","React stage effect failed":"React 舞台效果曾失败","Generic SaaS cards weakened hierarchy":"通用 SaaS 卡片削弱了层级"}[title] || title,title)}</strong><small>{id}</small></div><span>RANK {score}</span></div>)}</div>)}</section><aside className="context-side"><div className="terminal-panel budget-card"><div className="budget-ring"><Gauge/><strong>65%</strong><span>{c("上下文已使用","CONTEXT USED")}</span></div><dl><div><dt>{c("预算","Budget")}</dt><dd>12,000</dd></div><div><dt>{c("已注入","Injected")}</dt><dd>7,800</dd></div><div><dt>{c("预留","Reserved")}</dt><dd>2,400</dd></div><div><dt>{c("可用","Available")}</dt><dd>1,800</dd></div></dl></div><div className="terminal-panel excluded"><h3><EyeOff/>{c("治理器排除","EXCLUDED BY GOVERNOR")}</h3><p>{c("11 个低相关对象被保留在当前上下文之外。", "11 low-relevance objects kept outside the active context.")}</p>{[c("已归档 UI 实验","Archived UI experiments"),c("未验证的智能体推断","Unverified agent inference"),c("无关 OTC 资产","Unrelated OTC assets")].map(x=><span key={x}>{x}<b>{c("低排名","LOW RANK")}</b></span>)}</div><div className="terminal-panel governor"><BrainCircuit/><div><span>{c("治理器状态","GOVERNOR STATUS")}</span><strong>{c("上下文一致","Context is coherent")}</strong><small>{c("未检测到权威冲突","No authority conflicts detected")}</small></div></div></aside></div></div>}
